#include "test_helper.hpp"

DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 00);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 01);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 02);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 03);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 04);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 05);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 06);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 07);

DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 08);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 09);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 0a);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 0b);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 0c);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 0d);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 0e);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 0f);

DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RL, 10);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RL, 11);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RL, 12);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RL, 13);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RL, 14);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RL, 15);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RL, 16);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RL, 17);

DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RR, 18);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RR, 19);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RR, 1a);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RR, 1b);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RR, 1c);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RR, 1d);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RR, 1e);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RR, 1f);
