#include "test_helper.hpp"

DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 00);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 01);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 02);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 03);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 04);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 05);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 06);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 07);

DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 08);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 09);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 0a);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 0b);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 0c);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 0d);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 0e);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 0f);

DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RL, 10);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RL, 11);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RL, 12);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RL, 13);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RL, 14);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RL, 15);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RL, 16);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RL, 17);

DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RR, 18);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RR, 19);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RR, 1a);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RR, 1b);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RR, 1c);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RR, 1d);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RR, 1e);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RR, 1f);

DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SLA, 20);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SLA, 21);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SLA, 22);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SLA, 23);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SLA, 24);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SLA, 25);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SLA, 26);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SLA, 27);

DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SRA, 28);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SRA, 29);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SRA, 2a);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SRA, 2b);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SRA, 2c);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SRA, 2d);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SRA, 2e);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SRA, 2f);

DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SWAP, 30);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SWAP, 31);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SWAP, 32);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SWAP, 33);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SWAP, 34);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SWAP, 35);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SWAP, 36);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SWAP, 37);

DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SRL, 38);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SRL, 39);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SRL, 3a);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SRL, 3b);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SRL, 3c);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SRL, 3d);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SRL, 3e);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_SRL, 3f);
