#include "test_helper.hpp"

DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 00);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 01);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 02);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 03);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 04);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 05);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 06);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RLC, 07);

DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 08);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 09);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 0a);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 0b);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 0c);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 0d);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 0e);
DEFINE_TEST_CB(SINGLE_STEP_TESTS_SM83_RRC, 0f);
