#include "test_helper.hpp"

// ADD
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_ADD, 80);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_ADD, 81);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_ADD, 82);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_ADD, 83);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_ADD, 84);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_ADD, 85);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_ADD, 86);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_ADD, 87);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_ADD, 09);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_ADD, 19);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_ADD, 29);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_ADD, 39);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_ADD, c6);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_ADD, e8);
