#include "common.hpp"
#include "decoder.hpp"
#include "executor.hpp"
#include "simple_bus.hpp"
#include <cstdint>
#include <fstream>
#include <gtest/gtest.h>
#include <nlohmann/json.hpp>

using json = nlohmann::json;

namespace
{
  CpuState CreateStateFromJson(const auto &cpuState)
  {
    CpuState state{};
    state.AF.low = cpuState["f"];
    state.AF.high = cpuState["a"];
    state.BC.low = cpuState["c"];
    state.BC.high = cpuState["b"];
    state.DE.low = cpuState["e"];
    state.DE.high = cpuState["d"];
    state.HL.low = cpuState["l"];
    state.HL.high = cpuState["h"];
    state.SP.reg = cpuState["sp"];
    state.PC.reg = cpuState["pc"];
    state.t_cycles = 0;
    return state;
  }

  CpuState CreateInitialStateFromJson(const auto &test)
  {
    return CreateStateFromJson(test["initial"]);
  }

  CpuState CreateFinalStateFromJson(const auto &test)
  {
    auto state = CreateStateFromJson(test["final"]);
    state.t_cycles = test["cycles"].size() * 4;
    return state;
  }

  void InitializeBusFromJson(auto &bus, const auto &cpuState)
  {
    for (const auto &memState : cpuState["ram"])
    {
      uint16_t loc = memState[0];
      uint8_t data = memState[1];
      bus.Write(loc, data);
    }
  }
}// namespace


// helper macros
#define STRINGIFY(x) #x
#define EXPAND_AND_STRINGIFY(x) STRINGIFY(x)

// Define the test macro
#define DEFINE_TEST(TEST_SUITE_NAME, TEST_NAME)                                                               \
  TEST(TEST_SUITE_NAME, TEST_NAME)                                                                            \
  {                                                                                                           \
    std::ifstream file{ "data/" EXPAND_AND_STRINGIFY(TEST_NAME) ".json" };                                    \
    ASSERT_TRUE(file.is_open());                                                                              \
    json tests = json::parse(file);                                                                           \
    SimpleBus bus{};                                                                                          \
    Executor executor;                                                                                        \
    Decoder decoder;                                                                                          \
    for (const auto &test : tests)                                                                            \
    {                                                                                                         \
      auto initialState = CreateInitialStateFromJson(test);                                                   \
      auto finalState = CreateFinalStateFromJson(test);                                                       \
      bus.Reset();                                                                                            \
      InitializeBusFromJson(bus, test["initial"]);                                                            \
      auto opcode = bus.Read(initialState.PC.reg++);                                                          \
      decoder.DecodeAndExecute(opcode, initialState, bus, executor);                                          \
      ASSERT_EQ(initialState, finalState)                                                                     \
        << std::format("Test Name: {} [Final State does not match]", static_cast<std::string>(test["name"])); \
      for (const auto &memState : test["final"]["ram"])                                                       \
      {                                                                                                       \
        uint16_t loc = memState[0];                                                                           \
        uint8_t data = memState[1];                                                                           \
        ASSERT_EQ(bus.Read(loc), data) << std::format(                                                        \
          "Test Name: {} [Memory State Does not Match]", static_cast<std::string>(test["name"]));             \
      }                                                                                                       \
    }                                                                                                         \
  }

DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 00);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 01);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 02);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 03);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 04);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 05);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 06);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 07);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 08);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 09);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 0a);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 0b);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 0c);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 0d);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 0e);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 0f);


DEFINE_TEST(SINGLE_STEP_TESTS_SM83, DISABLED_10); // TODO: find why there are extra cycles in test
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 11);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 12);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 13);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 14);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 15);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 16);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 17);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 18);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 19);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 1a);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 1b);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 1c);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 1d);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 1e);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 1f);


DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 20);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 21);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 22);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 23);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 24);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 25);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 26);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 27);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 28);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 29);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 2a);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 2b);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 2c);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 2d);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 2e);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 2f);

DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 30);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 31);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 32);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 33);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 34);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 35);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 36);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 37);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 38);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 39);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 3a);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 3b);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 3c);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 3d);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 3e);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 3f);

DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 40);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 41);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 42);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 43);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 44);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 45);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 46);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 47);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 48);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 49);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 4a);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 4b);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 4c);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 4d);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 4e);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 4f);

DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 50);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 51);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 52);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 53);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 54);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 55);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 56);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 57);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 58);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 59);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 5a);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 5b);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 5c);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 5d);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 5e);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 5f);

DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 60);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 61);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 62);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 63);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 64);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 65);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 66);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 67);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 68);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 69);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 6a);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 6b);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 6c);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 6d);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 6e);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 6f);

DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 70);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 71);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 72);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 73);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 74);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 75);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, DISABLED_76); // TODO: unskip this test once halt instruction is implemented
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 77);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 78);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 79);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 7a);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 7b);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 7c);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 7d);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 7e);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 7f);

DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 80);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 81);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 82);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 83);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 84);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 85);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 86);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 87);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 88);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 89);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 8a);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 8b);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 8c);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 8d);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 8e);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 8f);

DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 90);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 91);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 92);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 93);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 94);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 95);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 96);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 97);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 98);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 99);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 9a);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 9b);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 9c);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 9d);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 9e);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, 9f);

DEFINE_TEST(SINGLE_STEP_TESTS_SM83, a0);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, a1);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, a2);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, a3);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, a4);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, a5);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, a6);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, a7);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, a8);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, a9);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, aa);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, ab);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, ac);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, ad);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, ae);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, af);

DEFINE_TEST(SINGLE_STEP_TESTS_SM83, b0);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, b1);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, b2);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, b3);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, b4);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, b5);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, b6);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, b7);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, b8);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, b9);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, ba);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, bb);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, bc);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, bd);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, be);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, bf);

DEFINE_TEST(SINGLE_STEP_TESTS_SM83, c0);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, c1);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, c2);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, c3);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, c4);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, c5);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, c6);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, c7);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, c8);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, c9);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, ca);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, DISABLED_cb); // TODO: implement prefix instruction
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, cc);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, cd);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, ce);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83, cf);
