#include "test_helper.hpp"

DEFINE_TEST(SINGLE_STEP_TESTS_SM83_RLCA, 07);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_RRCA, 0f);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_RLA, 17);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_RRA, 1f);
