#include "test_helper.hpp"

DEFINE_TEST(SINGLE_STEP_TESTS_SM83_NOP, 00);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_STOP, DISABLED_10);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_HALT, DISABLED_76);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_DI, f3);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_EI, fb);
