#include "test_helper.hpp"

// JP
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_JP, c2);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_JP, c3);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_JP, ca);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_JP, d2);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_JP, da);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_JP, e9);

// JR
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_JR, 18);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_JR, 20);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_JR, 28);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_JR, 30);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_JR, 38);

// CALL
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_CALL, c4);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_CALL, cc);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_CALL, cd);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_CALL, d4);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_CALL, dc);

// RET
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_RET, c0);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_RET, c8);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_RET, c9);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_RET, d0);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_RET, d8);

// RETI
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_RETI, d9);

// RST
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_RST, c7);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_RST, cf);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_RST, d7);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_RST, df);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_RST, e7);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_RST, ef);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_RST, f7);
DEFINE_TEST(SINGLE_STEP_TESTS_SM83_RST, ff);
